export const environment = {
  production: false,
  desenvolvimento: false,
  homologacao: true,
  apiUrl: 'https://hml-aut-api.sura-aws.com/hml',
  apiUrlCor: 'https://hml-cor-api.sura-aws.com/hml',
  apiAuto: 'https://hml-aut-backend.sura-aws.com',
  apiAutoUnicoCF: 'https://hml-aut-api.sura-aws.com/hml',
  cotacao: 123,
  visualizar: 456,
  consultar: 789,
  integracao: 1011,
  versao: 1213,
  apiBackendPrj: 'https://hml-cor-backend.sura-aws.com',
  editar: 1415,
  getnet_token: 'https://api-sura.sensedia.com/uat/v1/getnet-auth',
  getnet: 'https://api-sura.sensedia.com/uat/getnet/v1/',
  get_pedido: 'https://hml-backend.sura-aws.com/',
  client_id: '6dd955b1-40e7-31c2-adb2-05eb35f66e3a',
  basic_token: 'NmRkOTU1YjEtNDBlNy0zMWMyLWFkYjItMDVlYjM1ZjY2ZTNhOjI3MWY4M2VjLTkwZjQtMzY4ZC1iMzk1LTQwMmNmYjEzM2Q0Zg==',
  cartao_acess_token: 'https://api-sura.sensedia.com/uat/v1/cartao-credito-auth',
  client_id_cartao: '4ce6af1a-2e9f-4fd1-90c1-0e4946dfebb2',
  basic_token_cartao: 'NGNlNmFmMWEtMmU5Zi00ZmQxLTkwYzEtMGU0OTQ2ZGZlYmIyOmI0NTUwNGFhLWY3MDgtNDE1MS05ZDljLTJiYTU2NTE1MGMwOQ==',
  apiCartao: 'https://api-sura.sensedia.com/uat/cartao-credito',
  bearerToken: 'https://oichomologacao.segurossura.com.br',
  googleAnalytics: {
    id: 'G-CEMKK7K3C7',
  },
};
